services:
  app:
    image: bitnami/laravel:latest
    user : root
    container_name: hyperion_app
    restart: unless-stopped
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - ./server/HyperionServer:/app
    environment:
      - DB_HOST=db
      - DB_DATABASE=Hyperion
      - DB_USERNAME=root
      - DB_PASSWORD=afterlife
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: hyperion_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: Hyperion
      MYSQL_ROOT_PASSWORD: afterlife

    ports:
      - "33066:3306"
    volumes:
      - hyperion_db_data:/var/lib/mysql

volumes:
  hyperion_db_data: {}

